module.exports = {
  up: (queryInterface) => queryInterface.bulkInsert(
    'Users',
    [
              {
                id: 1,
                firstName: 'Josh@gmail.com',
                lastName: 'Josh@gmail.com',
                email: 'Josh@gmail.com',
                password: '$2b$10$KEVMx4HkwC0UtVT6Ev9M7ua0ODQfKqA1BoAxcz9p/tq3AQQYs8EJ6',
                dateOfBirth: '1/1/2020',
                gender: 'Male',
                address: 'Kanombe',
                role: 'admin',
                isLoggedIn: true,
                createdAt: new Date(),
                updatedAt: new Date(),
              },
              {
                id: 30,
                firstName: 'Josh@gmail.com',
                lastName: 'Josh@gmail.com',
                email: 'Josh123@gmail.com',
                password: '$2b$10$KEVMx4HkwC0UtVT6Ev9M7ua0ODQfKqA1BoAxcz9p/tq3AQQYs8EJ6',
                dateOfBirth: '1/1/2020',
                gender: 'Male',
                address: 'Kanombe',
                role: 'operator',
                isLoggedIn: true,
                createdAt: new Date(),
                updatedAt: new Date(),
              },
     
      {
        id: 31,
        firstName: 'Josh@gmail.com',
        lastName: 'Josh@gmail.com',
        email: 'Josh3000@gmail.com',
        password: '$2b$10$KEVMx4HkwC0UtVT6Ev9M7ua0ODQfKqA1BoAxcz9p/tq3AQQYs8EJ6',
        dateOfBirth: '1/1/2020',
        gender: 'Male',
        address: 'Kanombe',
        role: 'driver',
        isLoggedIn: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        firstName: 'Allybomayee',
        lastName: 'Babalao',
        email: 'el.ally741@gmail.com',
        password: '$2b$10$KEVMx4HkwC0UtVT6Ev9M7ua0ODQfKqA1BoAxcz9p/tq3AQQYs8EJ6',
        dateOfBirth: '1/1/2020',
        gender: 'Male',
        address: 'Kanombe',
        role: 'admin',
        isLoggedIn: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

       {
        id: 3,
        firstName: 'Wlly ',
        lastName: 'Smith',
        email: 'wil@gmail.com',
        password: '$2y$12$73vIIygHIADwU/m.DVOPIuqTI7T0jZSYsNbrQjK6HrSFoddtiioIq',
        dateOfBirth: '1/1/2020',
        gender: 'Male',
        address: 'Kanombe',
        role: 'admin',
        isLoggedIn: true,
        createdAt: new Date(),
        updatedAt: new Date(),
       },
      {
        id: 12,
        firstName: 'Will',
        lastName: 'John',
        email: 'will@gmail.com',
        password: '$2y$12$RdAQ9sf4r2BM2k.qfo94..324UEcl0XLF0vCkVZuNVS3xQfKchcTq',
        dateOfBirth: '1/1/2020',
        gender: 'Male',
        address: 'Kanombe',
        role: 'operator',
        isLoggedIn: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
        {
        id: 10,
        email: "mugema8@gmail.com",
        password:"$2b$10$w7q8hFgkKfuhXw3og.Uau.jkY3XfP94GnhJpWvuBBmWJioEA0669y",
        firstName: "Henry",
        lastName: "ntare",
        dateOfBirth: "1/1/2000",
        gender: "1/1/2000",
        address: "Kabeza",
        role: "driver",
        isLoggedIn: true,
        createdAt: new Date(),
        updatedAt: new Date(),
},
      {
        id: 9,
        firstName: 'Atalaku',
        lastName: 'Convoyeur',
        email: 'el.ally742dereva@gmail.com',
        password: '$2b$10$KEVMx4HkwC0UtVT6Ev9M7ua0ODQfKqA1BoAxcz9p/tq3AQQYs8EJ6',
        dateOfBirth: '1/1/2020',
        gender: 'Male',
        address: 'Kanombe',
        role: 'driver',
        isLoggedIn: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        firstName: 'Allybomayee',
        lastName: 'Babalao',
        email: 'el.ally741@gmail.com',
        password: '$2b$10$KEVMx4HkwC0UtVT6Ev9M7ua0ODQfKqA1BoAxcz9p/tq3AQQYs8EJ6',
        dateOfBirth: '1/1/2020',
        gender: 'Male',
        address: 'Kanombe',
        role: 'operator',
        isLoggedIn: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        firstName: 'bruce',
        lastName: 'Mark',
        email: 'bruce@gmail.com',
        password: '$2y$12$RvYDo5UzcJfODxQ.RezrFuI71lqW4wtL7BmSkx9ADfkwmiDNiXxY.',
        dateOfBirth: '1/1/2020',
        gender: 'Male',
        address: 'Kanombe',
        role: 'user',
        isLoggedIn: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        firstName: 'Jennie',
        lastName: 'Alice',
        email: 'jennie@gmail.com',
        password: '$2y$12$RdAQ9sf4r2BM2k.qfo94..324UEcl0XLF0vCkVZuNVS3xQfKchcTq',
        dateOfBirth: '1/1/2020',
        gender: 'Male',
        address: 'Kanombe',
        role: 'driver',
        isLoggedIn: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    {},
  ),

  down: (queryInterface) => queryInterface.bulkDelete('Users', null, {}),
};